# Generated by Django 4.2.7 on 2026-04-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_profile_change_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviour',
            name='headmaster_remarks',
            field=models.TextField(blank=True, help_text="Headmaster/Head teacher's remarks about the student"),
        ),
    ]
