# Generated by Django 4.2.7 on 2026-04-09 00:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_school_current_term'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0009_headmaster_remarks'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetype',
            name='allow_any_teacher_collection',
            field=models.BooleanField(default=False, help_text='Any teacher may collect this fee'),
        ),
        migrations.AddField(
            model_name='feetype',
            name='allow_class_teacher_collection',
            field=models.BooleanField(default=False, help_text='Class teachers may collect this fee for their own class'),
        ),
        migrations.AddField(
            model_name='feetype',
            name='collection_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Day of month (1-31) for MONTHLY, or day of week (0=Mon, 6=Sun) for WEEKLY', null=True),
        ),
        migrations.AddField(
            model_name='feetype',
            name='collection_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily (Every School Day)'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('TERM', 'Per Term'), ('YEAR', 'Per Year')], default='TERM', help_text='How often this fee is charged', max_length=10),
        ),
        migrations.AddField(
            model_name='feetype',
            name='require_payment_approval',
            field=models.BooleanField(default=False, help_text='Each payment requires admin verification before it is finalised'),
        ),
        migrations.CreateModel(
            name='TermBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_billed', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UNPAID', 'Not Paid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Fully Paid'), ('WAIVED', 'Waived')], default='UNPAID', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_bills', to=settings.AUTH_USER_MODEL)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='term_bills', to='fees.feetype')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_bills', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_bills', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_bills', to='schools.term')),
            ],
            options={
                'ordering': ['term', 'fee_type', 'student'],
                'unique_together': {('student', 'term', 'fee_type')},
            },
        ),
    ]
