# Generated by Django 4.2.7 on 2026-03-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allow_review',
            field=models.BooleanField(default=True, help_text='Allow students to review their submissions'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='has_mcq_questions',
            field=models.BooleanField(default=False, help_text='Quiz contains multiple choice questions'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='has_short_answer_questions',
            field=models.BooleanField(default=False, help_text='Quiz contains short answer questions'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='review_available_after',
            field=models.CharField(choices=[('IMMEDIATE', 'Immediately after submission'), ('GRADED', 'After teacher grades'), ('MANUAL', 'Manual teacher control'), ('NEVER', 'Never allow review')], default='GRADED', help_text='When students can review their submissions', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='review_enabled_at',
            field=models.DateTimeField(blank=True, help_text='When review was manually enabled', null=True),
        ),
    ]
