# Generated by Django 4.2.7 on 2026-04-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_school_current_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='parent_can_message_teachers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='parent_can_pay_fees_online',
            field=models.BooleanField(default=False, help_text='Allow parents to initiate online fee payments via Paystack'),
        ),
        migrations.AddField(
            model_name='school',
            name='parent_can_view_attendance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='parent_can_view_fees',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='parent_can_view_grades',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='parent_can_view_reports',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='parent_portal_enabled',
            field=models.BooleanField(default=False, help_text='Master switch — when off, no parent can log in'),
        ),
        migrations.AddField(
            model_name='school',
            name='parent_support_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='paystack_public_key',
            field=models.CharField(blank=True, help_text='Your Paystack public key (pk_live_... or pk_test_...)', max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='paystack_secret_key',
            field=models.CharField(blank=True, help_text='Your Paystack secret key — kept server-side only', max_length=100),
        ),
    ]
