# Generated by Django 4.2.7 on 2026-04-15 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_feetype_parent_studentfeesubtype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0009_fix_class_teacher_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='special_fee_collection_enabled',
            field=models.BooleanField(default=True, help_text='Master switch — when off, no special fee-collector teacher can see the fee collection page'),
        ),
        migrations.CreateModel(
            name='StaffPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_collect_fees', models.BooleanField(default=False)),
                ('fee_collection_enabled', models.BooleanField(default=True, help_text='Sub-toggle: turn off to hide fee collection from this teacher without removing the assignment')),
                ('can_cover_attendance', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collect_fee_types', models.ManyToManyField(blank=True, help_text='Leave empty to allow all active fee types', related_name='special_collectors', to='fees.feetype')),
                ('cover_classes', models.ManyToManyField(blank=True, help_text='Classes this teacher can cover for attendance', related_name='cover_teachers', to='schools.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_permissions', to='schools.school')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Permission',
                'db_table': 'staff_permissions',
                'unique_together': {('school', 'teacher')},
            },
        ),
    ]
