# Generated by Django 4.2.7 on 2026-04-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_staffpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='teachers_can_add_students',
            field=models.BooleanField(default=True, help_text='Master switch — when off, class teachers cannot add students; only admins can'),
        ),
    ]
