# Generated by Django 6.0.5 on 2026-05-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_sms_balance_purchase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='sms_sender_name',
            field=models.CharField(blank=True, default='SchoolSMS', help_text='SMS sender ID (max 11 alphanumeric chars, e.g. "MySchool")', max_length=11),
        ),
    ]
