# Generated by Django 4.2.7 on 2026-05-21 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('schools', '0015_add_financial_permission'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='budget',
            table='financial_budget',
        ),
        migrations.AlterModelTable(
            name='budgetitem',
            table='financial_budgetitem',
        ),
        migrations.AlterModelTable(
            name='expense',
            table='financial_expense',
        ),
        migrations.AlterModelTable(
            name='expenseapproval',
            table='financial_expenseapproval',
        ),
        migrations.AlterModelTable(
            name='paymentreminder',
            table='financial_paymentreminder',
        ),
        migrations.AlterModelTable(
            name='payrollrecord',
            table='financial_payrollrecord',
        ),
        migrations.AlterModelTable(
            name='staffsalary',
            table='financial_staffsalary',
        ),
        migrations.CreateModel(
            name='FinancialAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(blank=True, max_length=255)),
                ('object_repr', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('PAY', 'Payment'), ('GENERATE', 'Generate')], max_length=20)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_audit_logs', to='schools.school')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'financial_auditlog',
                'ordering': ['-timestamp'],
            },
        ),
    ]
